#!/usr/bin/env sh
set -eu

server_env_path="$(CDPATH= cd -- "$(dirname -- "$0")/../.." && pwd)/server/.env"

required_env() {
  name="$1"
  eval "value=\${$name:-}"
  if [ -z "$value" ]; then
    echo "Required azd environment variable '$name' was not set." >&2
    exit 1
  fi
  printf '%s' "$value"
}

set_dotenv_value() {
  file="$1"
  name="$2"
  value="$3"

  if grep -q "^$name=" "$file"; then
    tmp_file="${file}.tmp"
    awk -v key="$name" -v val="$value" 'BEGIN { prefix = key "=" } index($0, prefix) == 1 { print key "=" val; next } { print }' "$file" > "$tmp_file"
    mv "$tmp_file" "$file"
  else
    printf '%s=%s\n' "$name" "$value" >> "$file"
  fi
}

if [ ! -f "$server_env_path" ]; then
  {
    echo "# Azure OpenAI / Microsoft Foundry resource used by the realtime WebSocket proxy."
    echo "# Generated by azd postprovision. Edit optional realtime tuning values manually."
  } > "$server_env_path"
fi

set_dotenv_value "$server_env_path" "AZURE_OPENAI_RESOURCE_NAME" "$(required_env AZURE_OPENAI_RESOURCE_NAME)"
set_dotenv_value "$server_env_path" "AZURE_OPENAI_REALTIME_DEPLOYMENT" "$(required_env AZURE_OPENAI_REALTIME_DEPLOYMENT)"
set_dotenv_value "$server_env_path" "AZURE_OPENAI_REALTIME_TRANSLATION_MODEL" "$(required_env AZURE_OPENAI_REALTIME_TRANSLATION_MODEL)"
set_dotenv_value "$server_env_path" "AZURE_OPENAI_REALTIME_TRANSLATION_INPUT_TRANSCRIPTION_MODEL" "$(required_env AZURE_OPENAI_REALTIME_TRANSLATION_INPUT_TRANSCRIPTION_MODEL)"

echo "Updated server/.env with Azure OpenAI resource and realtime deployment names."
