$ErrorActionPreference = "Stop"

$serverEnvPath = Join-Path $PSScriptRoot "..\..\server\.env"
$webEnvPath = Join-Path $PSScriptRoot "..\..\.env.production"

function Get-RequiredEnvValue {
    param([string] $Name)

    $value = [Environment]::GetEnvironmentVariable($Name)
    if ([string]::IsNullOrWhiteSpace($value)) {
        throw "Required azd environment variable '$Name' was not set."
    }

    return $value
}

function Set-DotEnvValue {
    param(
        [string[]] $Lines,
        [string] $Name,
        [string] $Value
    )

    $escapedName = [regex]::Escape($Name)
    $updated = $false
    $result = @(foreach ($line in $Lines) {
        if ($line -match "^$escapedName=") {
            $updated = $true
            "$Name=$Value"
        } else {
            $line
        }
    })

    if (-not $updated) {
        $result += "$Name=$Value"
    }

    return $result
}

$values = @{
    "AZURE_OPENAI_RESOURCE_NAME" = Get-RequiredEnvValue "AZURE_OPENAI_RESOURCE_NAME"
    "AZURE_OPENAI_REALTIME_DEPLOYMENT" = Get-RequiredEnvValue "AZURE_OPENAI_REALTIME_DEPLOYMENT"
    "AZURE_OPENAI_REALTIME_TRANSLATION_MODEL" = Get-RequiredEnvValue "AZURE_OPENAI_REALTIME_TRANSLATION_MODEL"
    "AZURE_OPENAI_REALTIME_TRANSLATION_INPUT_TRANSCRIPTION_MODEL" = Get-RequiredEnvValue "AZURE_OPENAI_REALTIME_TRANSLATION_INPUT_TRANSCRIPTION_MODEL"
    "WEBSLIDES_EXPORT_ALLOWED_HOSTS" = Get-RequiredEnvValue "AZURE_STATIC_WEB_APP_HOSTNAME"
}
$webValues = @{
    "VITE_SERVER_URL" = Get-RequiredEnvValue "VITE_SERVER_URL"
}

$lines = if (Test-Path $serverEnvPath) {
    Get-Content -Path $serverEnvPath
} else {
    @(
        "# Azure OpenAI / Microsoft Foundry resource used by the realtime WebSocket proxy."
        "# Generated by azd postprovision. Edit optional realtime tuning values manually."
    )
}

foreach ($item in $values.GetEnumerator()) {
    $lines = Set-DotEnvValue -Lines $lines -Name $item.Key -Value $item.Value
}

Set-Content -Path $serverEnvPath -Value $lines -Encoding utf8
Write-Host "Updated server/.env with Azure OpenAI resource and realtime deployment names."

$webLines = if (Test-Path $webEnvPath) {
    Get-Content -Path $webEnvPath
} else {
    @(
        "# Generated by azd postprovision. Used by Vite during Static Web Apps builds."
    )
}

foreach ($item in $webValues.GetEnumerator()) {
    $webLines = Set-DotEnvValue -Lines $webLines -Name $item.Key -Value $item.Value
}

Set-Content -Path $webEnvPath -Value $webLines -Encoding utf8
Write-Host "Updated .env.production with the hosted Container Apps backend URL."
